### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by davidsetyanugraha** [IndoNLP/indonlu#1]
Hi Indobenchmark team,

Thanks for such an interesting project. 
Just curious. Is there a contributing guidelines for this project?

Many thanks,
David

**Comment by gentaiscool** [comment]
Hi David, we don't have the contributing guidelines yet, but you are welcome to send a pull request :)

**Comment by davidsetyanugraha** [comment]
Hi Genta,

Cool! Looking forward to do it.

**Comment by gentaiscool** [comment]
@davidsetyanugraha for your information, we just added https://github.com/indobenchmark/indonlu/blob/master/CONTRIBUTING.md 

thanks for the suggestion!
