### ISSUE TITLE
Documentation in Bahasa Indonesia

### ISSUE THREAD

**Issue by gentaiscool** [IndoNLP/indonlu#11]
Let's add a documentation in Indonesian.

**Comment by gentaiscool** [comment]
@davidsetyanugraha @SamuelCahyawijaya what do you think?

**Comment by gentaiscool** [comment]
@bryanwilie @karissaa any suggestions?

**Comment by bryanwilie** [comment]
By documentation, are you talking about the README.md, @gentaiscool ? Maybe this PR is sufficient: https://github.com/indobenchmark/indonlu/pull/12

**Comment by davidsetyanugraha** [comment]
To my understanding, github will always redirect to readme.md by default. So, I think PR #12 would be sufficient. In the future, we just need to make sure those 2 files are always up to date.

**Comment by bryanwilie** [comment]
Will merge end of day tomorrow then 👍🏻
