### ISSUE TITLE
need indobert cased pretrained model 

### ISSUE THREAD

**Issue by nunenuh** [IndoNLP/indonlu#13]
As I read from some article that cased BERT model is more accurate in part of speech tagging or NER type data. I hope the team will build a cased model for pretrained IndoBERT.

**Comment by gentaiscool** [comment]
Thank you for your suggestion @nunenuh It is a good idea. Hopefully, later we can train one once we have the bandwidth and resources.

**Comment by nunenuh** [comment]
Thank you for your response, I really appreciate it. I hope IndoNLU team will soon have the bandwidth and resources, I wish the best for the team.
