### ISSUE TITLE
Load Dataset Error

### ISSUE THREAD

**Issue by Aditrhn** [IndoNLP/indonlu#14]
## Expected Behavior
Load the data set at the prepare dataset stage can run smoothly without any errors
## Actual Behavior
When running it on my computer, the preprocessing data section has a problem, namely ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements

### Question
How do I fix the error? My dataset has 2 columns, namely a text column and a sentiment column. Each file has 7200 data in train.csv, 1000 data in valid.csv, and 1800 data in test.csv
![image](https://user-images.githubusercontent.com/33977433/100245749-fb0e7680-2f6a-11eb-9f43-c24091624297.png)
![a](https://user-images.githubusercontent.com/33977433/100245673-e631e300-2f6a-11eb-88cd-00c6c30ac5fc.PNG)

**Comment by SamuelCahyawijaya** [comment]
Hi @Aditrhn , I think it is because we use tsv instead of csv in the `DocumentSentimentDataset` class.  You can remove the `sep='\t'` parameter in the `pd.read_csv` function in order to read csv file.

https://github.com/indobenchmark/indonlu/blob/051af711eeb59ac6d96680b569c7f60443bc9f45/utils/data_utils.py#L510-L514

Also, if your csv file has column names on the top row, you might want to remove `header=None` parameter as well.

**Comment by Aditrhn** [comment]
Thanks for the reply @SamuelCahyawijaya , I've done the step above including removing the `header=none` parameter and the problem is already solve. But unfortunately I've found another error right after executing the code. 
![image](https://user-images.githubusercontent.com/33977433/100313021-4ca81700-2fe6-11eb-8d2d-5786638c8cb7.png)
![image](https://user-images.githubusercontent.com/33977433/100313049-5df12380-2fe6-11eb-9776-0cb11669ce4d.png)

My csv file has a column name, namely text for the text data, and sentiment for the label of the text. The label column is already in numeric. Should i change `df['sentiment'] = df['sentiment'].apply(lambda lab: self.LABEL2INDEX[lab])` from `LABEL2INDEX` to `INDEX2LABEL`?  Or is there anything else should i change? My dataset look like this :
![image](https://user-images.githubusercontent.com/33977433/100313606-91807d80-2fe7-11eb-9190-f27d0b0e6b97.png)

Sorry to ask a lot of things, its my first time. Thank you in advance.

**Comment by Aditrhn** [comment]
Nevermind, I already find the solution. Thanks a lot for the help! ^^
