### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by ilham-bintang** [IndoNLP/indonlu#17]
## Expected Behavior
I want to finetune `indobenchmark/indobert-base-p2` to work for text classification. I have dataset from several math courses/topic (peluang, integral, trigonometri, etc). Given ~1200 list of data (~10-20 example question row per courses).

I am using google colab FPU

### Dataframe head
![Screenshot 2020-12-16 at 11 43 32](https://user-images.githubusercontent.com/24639411/102302392-efbfd100-3f93-11eb-9b30-ead6fa872ac8.png)

I split into 3 files: train.csv, test.csv, valid.csv

Everythings work fine when following the `finetune_smsa.ipynb` sample code

## Actual Behavior
Encounter `Error CUDA error: device-side assert triggered` when run the train from https://github.com/indobenchmark/indonlu/blob/master/examples/finetune_smsa.ipynb
(line 14 under Fine tune section)

I really suspicious of google colab GPU config 

## Steps to Reproduce the Problem
  1. Follow the example code, change the data frame class

  ```
class PDataset(Dataset):
    NUM_LABELS = NUM_LABELS
    LABEL2INDEX = LABEL2INDEX
    INDEX2LABEL = INDEX2LABEL
    
    def load_dataset(self, path):
        df = pd.read_csv(path)
        df['lesson_id'] = df['lesson_id'].apply(lambda lesson_id: self.LABEL2INDEX[lesson_id])
        return df
    
    def __init__(self, dataset_path, tokenizer, no_special_token=False, *args, **kwargs):
        self.data = self.load_dataset(dataset_path)
        self.tokenizer = tokenizer
        self.no_special_token = no_special_token
        
    def __getitem__(self, index):
        data = self.data.loc[index,:]
        content, lesson_id = data['content'], data['lesson_id']
        
        subwords = self.tokenizer.encode(content, add_special_tokens=not self.no_special_token)
        return np.array(subwords), np.array(lesson_id), data['content']
    
    def __len__(self):
        return len(self.data)
```

Content loader

```
class PContentDataLoader(DataLoader):
    def __init__(self, max_seq_len=512, *args, **kwargs):
        super(PContentDataLoader, self).__init__(*args, **kwargs)
        self.collate_fn = self._collate_fn
        self.max_seq_len = max_seq_len
        
    def _collate_fn(self, batch):
        batch_size = len(batch)
        max_seq_len = max(map(lambda x: len(x[0]), batch))
        max_seq_len = min(self.max_seq_len, max_seq_len)
        
        subword_batch = np.zeros((batch_size, max_seq_len), dtype=np.int64)
        mask_batch = np.zeros((batch_size, max_seq_len), dtype=np.float32)
        sentiment_batch = np.zeros((batch_size, 1), dtype=np.int64)
        
        seq_list = []
        for i, (subwords, sentiment, raw_seq) in enumerate(batch):
            subwords = subwords[:max_seq_len]
            subword_batch[i,:len(subwords)] = subwords
            mask_batch[i,:len(subwords)] = 1
            sentiment_batch[i,0] = sentiment
            
            seq_list.append(raw_seq)
            
        return subword_batch, mask_batch, sentiment_batch, seq_list
```

  2. Error when running the train code

**Comment by SamuelCahyawijaya** [comment]
Hi @ilham-bintang, does the error come on the very first data during the training or it happens in random? 
Usually `Error CUDA error: device-side assert triggered` is caused by an access violation,  like invalid index to embedding or such. You can try to run the model in cpu first to get a better understanding of the error.

I am actually wondering the values for `NUM_LABELS`,  `LABEL2INDEX`, and `INDEX2LABEL` in your case?
Can you ensure that `NUM_LABELS` is the same as the length of `LABEL2INDEX` and `INDEX2LABEL`, while `LABEL2INDEX` and `INDEX2LABEL` have exactly the the same id-to-label and label-to-id pairs?

And next time, please also provide the stack trace so that we can get a better understanding of the issue.

**Comment by ilham-bintang** [comment]
Hi @SamuelCahyawijaya, thanks for following up on my issue. I am trying to use 12 class. But forget to config output layer.

I can solve the issue by adding these line

```
# Load Tokenizer and Config
tokenizer = BertTokenizer.from_pretrained('indobenchmark/indobert-base-p2')
config = BertConfig.from_pretrained('indobenchmark/indobert-base-p2')
config.num_labels = NUM_LABELS # <-- forget add this

# Instantiate model
model = BertForSequenceClassification.from_pretrained('indobenchmark/indobert-base-p2', config=config)
```
