### ISSUE TITLE
What exactly is the environment for this library

### ISSUE THREAD

**Issue by kenghweeng** [IndoNLP/indonlu#21]
## Expected Behavior
Was hoping to replicate https://github.com/indobenchmark/indonlu/blob/master/examples/finetune_ner_grit.ipynb
and get a finetuned model :)

## Actual Behavior
However, was faced with `ImportError` issues stemming from incompatible functions found from older versions of transformers. 

## Steps to Reproduce the Problem
  1. Just run the cells with transformers version 4.3.0
  2. Would love to know which versions of what dependencies was used?
  
I've read the paper, and would love to try out this amazing work on some corpus for a school project.

**Comment by SamuelCahyawijaya** [comment]
Hi @kenghweeng , thank you for reporting. I have just added the `requirements.txt` file, for this project we use `nltk==3.4.5` and `transformers==2.9.0`. Btw, may I know which function causing the error?
