### ISSUE TITLE
Reproduce FacQA Task Result

### ISSUE THREAD

**Issue by ryanpram** [IndoNLP/indonlu#25]
Hi IndoNLU team,

I have a problem when i'm trying to reproduce the result of indoNLU paper on FacQA task using indobert-lite-large pretained model. In the paper show the F1 score result is 69.47.
<img width="618" alt="Screen Shot 2021-05-10 at 21 44 33" src="https://user-images.githubusercontent.com/34083758/117975332-c6477d80-b358-11eb-9935-166836586220.png">

But when i'm trying to reproduce and submit the prediction result to codalab, i got 64.4 on F1 score.
<img width="781" alt="Screen Shot 2021-05-10 at 21 43 29" src="https://user-images.githubusercontent.com/34083758/117978012-99489a00-b35b-11eb-85cd-1fe0c2020e2d.png">
The difference between my result and the result reported on the paper is about 5 point, which is i think its quite far.

What i do to reproduce the task is run https://github.com/indobenchmark/indonlu/blob/master/main.py code. For the hyperparameters, i follow what is written in the paper.
<img width="645" alt="Screen Shot 2021-05-10 at 21 34 48" src="https://user-images.githubusercontent.com/34083758/117976808-605bf580-b35a-11eb-9124-6a300d8a42eb.png">

I run the main.py code  as shown bellow:
![Screen Shot 2021-05-12 at 19 46 23](https://user-images.githubusercontent.com/34083758/117977193-c34d8c80-b35a-11eb-8845-a6c0cfaf8537.png)

Are there some configuration that i missed? 

Thank you in advance.

**Comment by gentaiscool** [comment]
Hi Ryan, thank you for reaching us.

It may be caused by different versions of your _transformers_ library or _CUDA_. 
Would you please check the requirements.txt to set up the environment https://github.com/indobenchmark/indonlu/blob/master/requirements.txt ?

Let us know if you have other questions.

Thank you

**Comment by ryanpram** [comment]
Hi @gentaiscool, big thanks for the answer.
I already make sure that i have used the right version for transformers library as written in the https://github.com/indobenchmark/indonlu/blob/master/requirements.txt . Maybe it is due to the difference in the CUDA version since i am running it in gcolab.
