### ISSUE TITLE
[Question] [Help Needed] local variable 'subword_batch' referenced before assignment

### ISSUE THREAD

**Issue by rhiosutoyo** [IndoNLP/indonlu#26]
Hi, thank you to IndoBenchmark Team for the tutorial, example codes, and efforts of IndoBERT model.
I have successfully run the "finetune_smsa.ipynb" provided in the examples folder. 

**Furthermore, I would like to learn and finetune the emotions recognition for "emot_emotion-twitter" dataset.**

Thus, I try to modify the sentiment analysis code. In my code, I have used EmotionDetectionDataset and EmotionDetectionDataLoader for dataset preparations. Nevertheless, when I try to run the "Fine Tuning & Evaluation" part, I got this error: "local variable 'subword_batch' referenced before assignment"

At first I thought I failed to prepare the datasets. Thus, I have double checked the "train_loader" with this "len(train_loader)" and got 3,521; which indicates it is not empty and should be passed to the "forward_sequence_classification" function. 

**Is there something that I miss to change for the emotions recognition? 
And how can I solve this issue? Thank you in advance. 🙏**

![image](https://user-images.githubusercontent.com/13897266/120224954-92cc8480-c26e-11eb-8816-650b51166628.png)

Here is the file of my Google Notebook (Collab) if needed:
[indo-bert.zip](https://github.com/indobenchmark/indonlu/files/6571571/indo-bert.zip)

**Comment by SamuelCahyawijaya** [comment]
Hi @rhiosutoyo, I tried to change the `DocumentSentimentDataset` and `DocumentSentimentDataLoader` in`finetune_smsa.ipynb` into `EmotionDetectionDataset ` and  `EmotionDetectionDataLoader `, and change the data path on line 7 into the emotion dataset:

```
train_dataset_path = './dataset/emot_emotion-twitter/train_preprocess.csv'
valid_dataset_path = './dataset/emot_emotion-twitter/valid_preprocess.csv'
test_dataset_path = './dataset/emot_emotion-twitter/test_preprocess_masked_label.csv'
```

and it seems to work just fine. You can check the notebook on the following URL:
https://github.com/indobenchmark/indonlu/blob/develop/examples/finetune_emot.ipynb

Hope it helps.

**Comment by rhiosutoyo** [comment]
Hi @SamuelCahyawijaya, thank you for the examples. My training is running well now,
The problem is indeed my train_loader, I put "train_dataset_path" instead of "dataset=train_dataset" in the first parameter of "EmotionDetectionDataLoader".
