### ISSUE TITLE
ValueError('Expected input batch_size ({}) to match target batch_size ({}).' ValueError: Expected input batch_size (3208) to match target batch_size (3784).

### ISSUE THREAD

**Issue by ryanpram** [IndoNLP/indonlu#28]
Hi indonlu team,

I got this error when i run task for facqa:
ValueError('Expected input batch_size ({}) to match target batch_size ({}).' ValueError: Expected input batch_size (3208) to match target batch_size (3784).

I got thats error when using my own dataset. My dataset has many long passage, so i think it's about wrong truncation process. this is my modification in QAFactoidDataLoader:
![image](https://user-images.githubusercontent.com/34083758/120915670-4d291500-c6cf-11eb-861d-6e75a5a15a47.png)

Can you help  or give some pointer to me for fixing this error?

Thanks in advance.

**Comment by SamuelCahyawijaya** [comment]
Hi @ryanpram, can you provide the following items to make the issue clearer?
1) The full stack trace of the error, it can be helpful for us to identify where this error arises
2) The sample of your dataset (you can also make a dummy file that follow your format)

Btw, just to make sure, QAFactoid should have the same length for passage and seq_label as it is a word-level sequence tagging task. Is it really what you are looking for?

If it is correct, I can think that there could be one possible problem if your document is too long, as we truncate the input from the left side for both input and output. In this case, you can do truncation from the right side instead, with a possibility of losing some / all parts of the question. You can check the following snippets where we apply the truncation:

https://github.com/indobenchmark/indonlu/blob/e216aab54a30d7693789d55430828f9771fd383e/utils/data_utils.py#L728-L729

As the limit of sequence length in the BERT model is 512, we cannot really do anything for longer input. You can also try to extend the positional embedding to a longer sequence length with randomly initialized position embedding vectors  as mentioned in this work: https://arxiv.org/pdf/1908.08345.pdf

**Comment by ryanpram** [comment]
Hi @SamuelCahyawijaya , thanks for the quick response and help. Yes, the problem is length of passage and seq_label doesn't match.I Forgot the sequence word will be tokenized into subword tokens. So i fix it with truncating the label as many as truncated word , not truncated token.

Once again thanks for your help. 
Cheers
