### ISSUE TITLE
HTTPs Certificate for indobenchmark expired

### ISSUE THREAD

**Issue by oonid** [IndoNLP/indonlu#31]
hello, hope you guys well.
as mentioned, your https certificate for indobenchmark website expired.
hope the project still continues and the certificate gets updated.

**Comment by SamuelCahyawijaya** [comment]
@oonid : Thank you for informing us about the website. Yes, we are still continuing our work. Stay tuned! 

And, sure, we will update the certificate for the website soon.

Thank you
