### ISSUE TITLE
Test split in the Emot

### ISSUE THREAD

**Issue by isspek** [IndoNLP/indonlu#34]
Thank you so much for the tool. I have a question on the Emot dataset. I have observed that the test set contains only one label: "happy". For fair evaluation, I think the test set contains samples from the other labels too. I wonder whether wrong test set was uploaded or it is a design choice. 

## Expected Behavior
the test split should have samples from each label
## Actual Behavior
the test set has only one label: `happy`
## Steps to Reproduce the Problem
N/A, i got it from the dataset analysis.

**Comment by SamuelCahyawijaya** [comment]
Hi @isspek: The test set from all tasks that we shared only consists of one label as we would like to ensure a comparable comparison by allowing the evaluation on the test set via Codalab submission which you can find on this [link](https://competitions.codalab.org/competitions/26537).

You can see how we produce the prediction file form our example notebooks that you can find in https://github.com/indobenchmark/indonlu/tree/master/examples.

Hope it helps!
