### ISSUE TITLE
Make this open source to meet github recommended community standard.

### ISSUE THREAD

**Issue by davidsetyanugraha** [IndoNLP/indonlu#5]
Please see checklist here: https://github.com/indobenchmark/indonlu/community

- [x] Code of conduct
- [x] Issue templates
- [x] Pull request template
- [x] Adjust readme
- [x] Repository admins accept content reports

**Comment by davidsetyanugraha** [comment]
Happy to create PR for this.

**Comment by gentaiscool** [comment]
@davidsetyanugraha yes you can! if you don't mind :)

**Comment by davidsetyanugraha** [comment]
No problem at all! I'll create PR later and let you guys know if it requires your admin access.

**Comment by SamuelCahyawijaya** [comment]
@davidsetyanugraha : Thank you!! Please let us know if there is anything you need from us
